
# File: `docker-compose.yml`
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=TestIkos
      - MONGO_COLLECTION=TestsModels
    depends_on:
      - mongo
    volumes:
      - ./:/app


